/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // M3 Semantic Colors - Extended for Expressive
        primary: '#002e5c',
        'on-primary': '#ffffff',
        'primary-container': '#dbe5f1', // Lighter blue for containers
        'on-primary-container': '#002e5c',

        secondary: '#ffde03',
        'on-secondary': '#000000',
        'secondary-container': '#ffde03',
        'on-secondary-container': '#000000',

        tertiary: '#5c6bc0', // Adding tertiary for accents logic
        'on-tertiary': '#ffffff',
        'tertiary-container': '#e0e0ff',
        'on-tertiary-container': '#1a237e',

        surface: '#fdfbff',
        'surface-dim': '#ded8e1',
        'surface-bright': '#fdfbff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f7f2fa',
        'surface-container': '#f3edf7',
        'surface-container-high': '#ece6f0',
        'surface-container-highest': '#e6e0e9',

        'on-surface': '#1b1b1f',
        'on-surface-variant': '#44474f',
        'outline': '#74777f',
        'outline-variant': '#c4c6cf',

        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#410002',

        slate: {
          50: 'var(--color-slate-50)',
          100: 'var(--color-slate-100)',
          200: 'var(--color-slate-200)',
          300: 'var(--color-slate-300)',
          400: 'var(--color-slate-400)',
          500: 'var(--color-slate-500)',
          600: 'var(--color-slate-600)',
          700: 'var(--color-slate-700)',
          800: 'var(--color-slate-800)',
          900: 'var(--color-slate-900)',
        },
        blue: {
          50: 'var(--color-pc-blue-50)',
          100: 'var(--color-pc-blue-100)',
          200: 'var(--color-pc-blue-200)',
          300: 'var(--color-pc-blue-300)',
          400: 'var(--color-pc-blue-400)',
          500: 'var(--color-pc-blue-500)',
          600: 'var(--color-pc-blue-600)',
          700: 'var(--color-pc-blue-700)',
          800: 'var(--color-pc-blue-800)',
          900: 'var(--color-pc-blue-900)',
        },
        orange: {
          50: 'var(--color-pc-orange-50)',
          100: 'var(--color-pc-orange-100)',
          200: 'var(--color-pc-orange-200)',
          300: 'var(--color-pc-orange-300)',
          400: 'var(--color-pc-orange-400)',
          500: 'var(--color-pc-orange-500)',
          600: 'var(--color-pc-orange-600)',
          700: 'var(--color-pc-orange-700)',
          800: 'var(--color-pc-orange-800)',
          900: 'var(--color-pc-orange-900)',
        },
        yellow: {
          50: 'var(--color-pc-yellow-50)',
          100: 'var(--color-pc-yellow-100)',
          200: 'var(--color-pc-yellow-200)',
          300: 'var(--color-pc-yellow-300)',
          400: 'var(--color-pc-yellow-400)',
          500: 'var(--color-pc-yellow-500)',
          600: 'var(--color-pc-yellow-600)',
          700: 'var(--color-pc-yellow-700)',
          800: 'var(--color-pc-yellow-800)',
          900: 'var(--color-pc-yellow-900)',
        },
        green: {
          50: 'var(--color-pc-green-50)',
          100: 'var(--color-pc-green-100)',
          200: 'var(--color-pc-green-200)',
          300: 'var(--color-pc-green-300)',
          400: 'var(--color-pc-green-400)',
          500: 'var(--color-pc-green-500)',
          600: 'var(--color-pc-green-600)',
          700: 'var(--color-pc-green-700)',
          800: 'var(--color-pc-green-800)',
          900: 'var(--color-pc-green-900)',
        },
        red: {
          50: 'var(--color-pc-red-50)',
          100: 'var(--color-pc-red-100)',
          200: 'var(--color-pc-red-200)',
          300: 'var(--color-pc-red-300)',
          400: 'var(--color-pc-red-400)',
          500: 'var(--color-pc-red-500)',
          600: 'var(--color-pc-red-600)',
          700: 'var(--color-pc-red-700)',
          800: 'var(--color-pc-red-800)',
          900: 'var(--color-pc-red-900)',
        },
      },
      borderRadius: {
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '28px',
      },
    },
  },
  plugins: [],
  darkMode: 'class',
}